---
- name: Validate Letsencrypt parameters
  ansible.builtin.assert:
    that:
      - puppeteers_plausible_ce_letsencrypt_email is string

- name: Ensure that /etc/letsencrypt is present
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create user directory for Letsencrypt certificates
  ansible.builtin.file:
    path: "{{ puppeteers_plausible_ce_system_user_home }}/.local/share/letsencrypt"
    state: directory
    recurse: true

- name: Generate podman command-line
  ansible.builtin.set_fact:
    podman_certbot_command: "sudo /usr/local/bin/plausible-nginx-service.sh stop ; /bin/podman run -p 8080:80 -v ~/.local/share/letsencrypt:/etc/letsencrypt:rw,Z docker.io/certbot/certbot certonly -v --non-interactive --standalone --agree-tos -m {{ puppeteers_plausible_ce_letsencrypt_email }} -d {{ puppeteers_plausible_ce_server_name }}; sudo /usr/local/bin/plausible-nginx-service.sh start"

- name: Ensure initial Letsencrypt certificate
  ansible.builtin.shell:
    cmd: "test -h ~/.local/share/letsencrypt/live/{{ puppeteers_plausible_ce_server_name }}/fullchain.pem || {{ podman_certbot_command }}"
  become: true
  become_user: "{{ puppeteers_plausible_ce_system_user }}"

- name: Add cronjob for renewing Letsencrypt renewals
  ansible.builtin.cron:
    name: "Run certbot"
    job: "{{ podman_certbot_command }}"
    hour: "2"
    minute: "45"
    weekday: "1"
  become: true
  become_user: "{{ puppeteers_plausible_ce_system_user }}"

- name: Add cronjob to copy Letsencrypt certs to /etc/letsencrypt
  ansible.builtin.cron:
    name: "Copy Letsencrypt certs to /etc/letsencrypt"
    job: "rsync -rl {{ puppeteers_plausible_ce_system_user_home }}/.local/share/letsencrypt /etc/ && restorecon -rF /etc/letsencrypt && systemctl reload nginx"
    hour: "2"
    minute: "55"
    weekday: "1"
