---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - puppeteers_plausible_ce_system_user is string
      - puppeteers_plausible_ce_system_user_home is string
      - puppeteers_plausible_ce_ssh_authorized_key is string
      - puppeteers_plausible_ce_server_name is string
      - puppeteers_plausible_ce_base_url is string
      - puppeteers_plausible_ce_secret_key_base is defined
      - puppeteers_plausible_ce_http_port is number
      - puppeteers_plausible_ce_mailer_email is string
      - puppeteers_plausible_ce_mailer_name is string
      - puppeteers_plausible_ce_smtp_host_addr is string
      - puppeteers_plausible_ce_smtp_host_port is number
      - puppeteers_plausible_ce_smtp_user_name is string
      - puppeteers_plausible_ce_smtp_user_pwd is defined
      - puppeteers_plausible_ce_smtp_host_ssl_enabled is boolean

- name: Create unprivileged system user for plausible
  ansible.builtin.import_role:
    name: puppeteers.users.unprivileged_user
  vars:
    puppeteers_users_unprivileged_user_name: "{{ puppeteers_plausible_ce_system_user }}"
    puppeteers_users_unprivileged_user_comment: "Unprivileged user created for running plausible"
    puppeteers_users_unprivileged_user_home: "{{ puppeteers_plausible_ce_system_user_home }}"
    puppeteers_users_unprivileged_user_ssh_authorized_key: "{{ puppeteers_plausible_ce_ssh_authorized_key }}"

- name: Add script for restarting nginx
  ansible.builtin.template:
    src: templates/plausible-nginx-service.sh.j2
    dest: /usr/local/bin/plausible-nginx-service.sh
    owner: root
    group: root
    mode: "0755"

- name: Allow plausible user to restart nginx
  ansible.builtin.template:
    src: templates/90-plausible.j2
    dest: /etc/sudoers.d/90-plausible
    owner: root
    group: root
    mode: "0640"

- name: Ensure that prerequisites are installed
  ansible.builtin.package:
    name:
      - podman
      - rsync
      - git
    state: present

- name: Install acl to ensure that Ansible is able to run as plausible user
  ansible.builtin.package:
    name: acl
    state: present

- name: Download container images from Docker Hub by default to avoid interactive prompts
  ansible.builtin.lineinfile:
    state: present
    regexp: "^unqualified-search-registries = "
    line: "unqualified-search-registries = [\"docker.io\"]"
    path: /etc/containers/registries.conf

- name: Manage firewalld rules, including port forwarding
  ansible.builtin.import_tasks: firewalld.yml
  when: puppeteers_plausible_ce_manage_firewalld

- name: Manage certbot and letsencrypt renewal
  ansible.builtin.import_tasks: letsencrypt.yml
  when: puppeteers_plausible_ce_manage_letsencrypt

- name: Clone plausible-ce repository
  ansible.builtin.git:
    repo: https://github.com/Puppet-Finland/community-edition.git
    version: selinux_fix
    dest: "{{ puppeteers_plausible_ce_system_user_home }}/plausible-ce"
  become: true
  become_user: "{{ puppeteers_plausible_ce_system_user }}"

- name: Manage Plausible configuration (.env)
  ansible.builtin.template:
    src: templates/env.j2
    dest: "{{ puppeteers_plausible_ce_system_user_home }}/plausible-ce/.env"
    owner: "{{ puppeteers_plausible_ce_system_user }}"
    group: "{{ puppeteers_plausible_ce_system_user }}"
    mode: "0640"

- name: Manage Plausible compose.override.yml
  ansible.builtin.template:
    src: templates/compose.override.yml.j2
    dest: "{{ puppeteers_plausible_ce_system_user_home }}/plausible-ce/compose.override.yml"
    owner: "{{ puppeteers_plausible_ce_system_user }}"
    group: "{{ puppeteers_plausible_ce_system_user }}"
    mode: "0640"

- name: Ensure that /etc/letsencrypt is present
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Remove server settings from base nginx configuration
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: Add nginx configuration for Plausible
  ansible.builtin.template:
    src: templates/plausible.conf.j2
    dest: /etc/nginx/conf.d/plausible.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true

- name: Allow nginx to network connect in selinux
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
